feature: Hide `PosixDiskEnv` type behind a feature (default enabled)
dermesser/leveldb-rs pull request #38
Opened 2023-09-06 16:29 UTC by NumberFour8

Building `rusty-leveldb` in constrained or non-POSIX environments (such as WASM) is currently not possible.
This PR adds small changes to make it possible.

## Changes
- Introduces `fs` feature which is enabled by default. The feature allows to toggle the `PosixDiskEnv` type and therefore makes it possible to build `rusty-leveldb` on systems where `std::io` is constrained. One major use case are WASM environments. Users can therefore set `use-default-features = false` on `rusty-leveldb` dependency entries in their `Cargo.toml` .

- Updates `rand` crate to version `0.8.5` which is also WASM compatible. When the users of `rusty-leveldb` add `getrandom` dependency to their `Cargo.toml`, it will make the random number generation in `rusty-leveldb` work on their platform.

- Adds `crate-type` to allow builds in different environments

2023-09-07 09:17 UTC, dermesser commented
Thank you very much! I've left a few comments, but overall it looks good.

2023-09-07 09:18 UTC, dermesser requested changes

2023-09-07 09:18 UTC, dermesser commented on src/lib.rs
> +pub use env::{Env, FileLock, RandomAccess, Logger};
maybe it is better to instead change it to `pub mod env`, as the `FileLock, RandomAccess, Logger` types don't need to appear in the top level of the crate

2023-09-07 09:18 UTC, dermesser commented on src/options.rs
> +type CurrentEnv = crate::disk_env::PosixDiskEnv;
can you change it to `DefaultEnv` to clarify that it is not the one and only environment, but merely the default?

2023-09-07 10:01 UTC, NumberFour8 commented
> Thank you very much! I've left a few comments, but overall it looks good.

Thanks for the feedback :) I adapted the code according to your comments.

2023-09-12 19:48 UTC, NumberFour8 commented
@dermesser Is this good to merge, then?

2023-09-14 19:51 UTC, dermesser approved these changes

2023-09-14 19:51 UTC, merged

2023-09-14 19:52 UTC, dermesser commented
Yes apologies for the delay. I will shortly release a new major version